#ifndef APPLE_PLATFORM_H
#define APPLE_PLATFORM_H

/* Generated by cbindgen from crates/apple-platform-ffi. Do not edit by hand; regenerate with `just header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Incremented only on breaking changes to the C ABI (renamed/removed symbols,
 * changed signatures or struct layout). Adding functions is not a break.
 */
#define APPLE_PLATFORM_ABI_VERSION 1

#define APPLE_PLATFORM_OK 0

#define APPLE_PLATFORM_ERR_UNKNOWN 1

#define APPLE_PLATFORM_ERR_PANIC 2

#define APPLE_PLATFORM_ERR_INVALID_ARGUMENT 3

#define APPLE_PLATFORM_ERR_UNSUPPORTED 4

#define APPLE_PLATFORM_ERR_FEATURE_NOT_ENABLED 5

#define APPLE_PLATFORM_ERR_INTERACTIVE_INPUT_REQUIRED 6

#define APPLE_PLATFORM_ERR_IO 7

#define APPLE_PLATFORM_ERR_CERTIFICATE 8

#define APPLE_PLATFORM_ERR_PRIVATE_KEY 9

#define APPLE_PLATFORM_ERR_NO_SIGNING_CERTIFICATE 10

#define APPLE_PLATFORM_ERR_SIGNING 11

#define APPLE_PLATFORM_ERR_VERIFICATION 12

#define APPLE_PLATFORM_ERR_TIMESTAMP 13

#define APPLE_PLATFORM_ERR_NOTARIZE 14

#define APPLE_PLATFORM_ERR_STAPLE 15

#define APPLE_PLATFORM_ERR_MACHO 16

#define APPLE_PLATFORM_ERR_BUNDLE 17

#define APPLE_PLATFORM_ERR_DMG 18

#define APPLE_PLATFORM_ERR_PKG 19

#define APPLE_PLATFORM_ERR_REMOTE_SIGNING 20

/**
 * A byte payload allocated by this library. Owned by Rust: callers must
 * release it with `apple_platform_buffer_free` exactly once and must not
 * touch `cap`. A `data == NULL, len == 0` buffer is valid and means "empty".
 */
typedef struct ApplePlatformBuffer {
  uint8_t *data;
  size_t len;
  size_t cap;
} ApplePlatformBuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI version of this library. Callers must check it before use.
 */
uint32_t apple_platform_abi_version(void);

/**
 * JSON report of package/ABI versions, enabled features, build target, and
 * upstream provenance (crate versions, git commit/describe of the submodule).
 *
 * # Safety
 *
 * `out` must point to writable, properly aligned storage for an
 * [`ApplePlatformBuffer`]. Its previous value is overwritten.
 */
int32_t apple_platform_versions(struct ApplePlatformBuffer *out);

/**
 * JSON map of upstream config type name -> accepted field names, reflected
 * from the compiled-in upstream sources at runtime.
 *
 * # Safety
 *
 * `out` must point to writable, properly aligned storage for an
 * [`ApplePlatformBuffer`]. Its previous value is overwritten.
 */
int32_t apple_platform_config_schema(struct ApplePlatformBuffer *out);

/**
 * JSON details of the most recent failure on this thread (or `null` if the
 * last guarded call succeeded). Read it before making further calls: every
 * guarded call, including this one, resets the slot.
 *
 * # Safety
 *
 * `out` must point to writable, properly aligned storage for an
 * [`ApplePlatformBuffer`]. Its previous value is overwritten.
 */
int32_t apple_platform_last_error_json(struct ApplePlatformBuffer *out);

/**
 * Release a buffer returned by this library. Safe to call on NULL or on an
 * already-freed (zeroed) buffer.
 *
 * # Safety
 *
 * `buf` must be null or point to a writable [`ApplePlatformBuffer`]. A
 * nonempty buffer must be one returned by this library and not yet freed.
 */
void apple_platform_buffer_free(struct ApplePlatformBuffer *buf);

/**
 * Set the capture level for upstream log output: 0=off, 1=error, 2=warn,
 * 3=info, 4=debug, 5=trace. Records accumulate in a bounded ring buffer.
 */
int32_t apple_platform_log_set_level(int32_t level);

/**
 * Drain captured log records as a JSON array (oldest first).
 *
 * # Safety
 *
 * `out` must point to writable, properly aligned storage for an
 * [`ApplePlatformBuffer`]. Its previous value is overwritten.
 */
int32_t apple_platform_log_drain(struct ApplePlatformBuffer *out);

/**
 * Sign the filesystem path named in `request_json` (Mach-O, bundle, DMG, or
 * XAR). The request embeds upstream's `SignConfig` verbatim plus
 * input/output paths and non-scoped options. Returns a small JSON result.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_result_json` must point to writable, properly
 * aligned storage for an [`ApplePlatformBuffer`]; its previous value is
 * overwritten.
 */
int32_t apple_platform_sign(const char *request_json, struct ApplePlatformBuffer *out_result_json);

/**
 * Sign an in-memory Mach-O. `data`/`data_len` is the input binary; the signed
 * binary is returned in `out_macho`.
 *
 * # Safety
 *
 * `data` must be null when `data_len` is zero or point to `data_len` readable
 * bytes for the duration of the call. `request_json` must point to a readable
 * NUL-terminated string. `out_macho` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_sign_macho_data(const uint8_t *data,
                                       size_t data_len,
                                       const char *request_json,
                                       struct ApplePlatformBuffer *out_macho);

/**
 * Classify a filesystem path as upstream sees it (mach-o, bundle, dmg, xar,
 * zip, other). JSON result. `path` is NUL-terminated OS-native path bytes,
 * not necessarily UTF-8.
 *
 * # Safety
 *
 * `path` must point to a readable NUL-terminated string for the duration of
 * the call. `out_json` must point to writable, properly aligned storage for
 * an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_path_type(const char *path, struct ApplePlatformBuffer *out_json);

/**
 * Read all code-signature entities from a signable path. The JSON is
 * upstream's `SignatureReader` entity serialization, passed through
 * verbatim except for path fields, which use the wire path form. `path` is
 * NUL-terminated OS-native path bytes, not necessarily UTF-8.
 *
 * # Safety
 *
 * `path` must point to a readable NUL-terminated string for the duration of
 * the call. `out_json` must point to writable, properly aligned storage for
 * an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_read_signature(const char *path, struct ApplePlatformBuffer *out_json);

/**
 * Verify a Mach-O's signature, returning a JSON array of problems (empty =
 * no problems found). Upstream documents this check as advisory, not a full
 * Apple-equivalent verifier. `path` is NUL-terminated OS-native path bytes,
 * not necessarily UTF-8.
 *
 * # Safety
 *
 * `path` must point to a readable NUL-terminated string for the duration of
 * the call. `out_json` must point to writable, properly aligned storage for
 * an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_verify_macho(const char *path, struct ApplePlatformBuffer *out_json);

/**
 * Submit a path to Apple's notary service. JSON result includes the
 * submission ID. Requires the `notarize` feature.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_json` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_notarize_submit(const char *request_json,
                                       struct ApplePlatformBuffer *out_json);

/**
 * Wait for a notarization submission to reach a terminal state.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_json` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_notarize_wait(const char *request_json,
                                     struct ApplePlatformBuffer *out_json);

/**
 * Fetch the notarization log for a submission ID.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_json` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_notarize_log(const char *request_json, struct ApplePlatformBuffer *out_json);

/**
 * List recent notarization submissions for the configured credentials.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_json` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_notarize_list(const char *request_json,
                                     struct ApplePlatformBuffer *out_json);

/**
 * Staple a notarization ticket to a bundle, DMG, or XAR at `path`. `path` is
 * NUL-terminated OS-native path bytes, not necessarily UTF-8.
 *
 * # Safety
 *
 * `path` must point to a readable NUL-terminated string for the duration of
 * the call.
 */
int32_t apple_platform_staple(const char *path);

/**
 * Generate a self-signed code-signing certificate. JSON result carries the
 * PEM certificate and key material.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_json` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_certificate_generate_self_signed(const char *request_json,
                                                        struct ApplePlatformBuffer *out_json);

/**
 * Analyze a DER-encoded X.509 certificate for Apple-specific properties
 * (profile, team ID, extensions). JSON result.
 *
 * # Safety
 *
 * `der` must be null when `der_len` is zero or point to `der_len` readable
 * bytes for the duration of the call. `out_json` must point to writable,
 * properly aligned storage for an [`ApplePlatformBuffer`]; its previous value
 * is overwritten.
 */
int32_t apple_platform_certificate_analyze(const uint8_t *der,
                                           size_t der_len,
                                           struct ApplePlatformBuffer *out_json);

/**
 * Parse a PKCS#12 archive, returning certificates (and key presence) as
 * JSON. `options_json` carries the password.
 *
 * # Safety
 *
 * `data` must be null when `data_len` is zero or point to `data_len` readable
 * bytes for the duration of the call. `options_json` must be null or point to
 * a readable NUL-terminated string. `out_json` must point to writable,
 * properly aligned storage for an [`ApplePlatformBuffer`]; its previous value
 * is overwritten.
 */
int32_t apple_platform_p12_parse(const uint8_t *data,
                                 size_t data_len,
                                 const char *options_json,
                                 struct ApplePlatformBuffer *out_json);

/**
 * Create a PKCS#12 archive from PEM key/certificates described in
 * `request_json`. The raw p12 bytes are returned in `out_p12`.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_p12` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_p12_create(const char *request_json, struct ApplePlatformBuffer *out_p12);

/**
 * Assemble a universal ("fat") binary from single-arch Mach-O files listed
 * in `request_json`. JSON result.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_json` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_macho_universal_create(const char *request_json,
                                              struct ApplePlatformBuffer *out_json);

/**
 * Build a minimal synthetic Mach-O (for tests and fixtures) and return its
 * bytes in `out_macho`.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_macho` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_macho_create_synthetic(const char *request_json,
                                              struct ApplePlatformBuffer *out_macho);

/**
 * Describe an on-disk bundle (identifier, type, main executable, Info.plist
 * highlights). JSON result. `path` is NUL-terminated OS-native path bytes,
 * not necessarily UTF-8.
 *
 * # Safety
 *
 * `path` must point to a readable NUL-terminated string for the duration of
 * the call. `out_json` must point to writable, properly aligned storage for
 * an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_bundle_info(const char *path, struct ApplePlatformBuffer *out_json);

/**
 * List a bundle's files as upstream classifies them. JSON result. `path` is
 * NUL-terminated OS-native path bytes, not necessarily UTF-8.
 *
 * # Safety
 *
 * `path` must point to a readable NUL-terminated string for the duration of
 * the call. `out_json` must point to writable, properly aligned storage for
 * an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_bundle_files(const char *path, struct ApplePlatformBuffer *out_json);

/**
 * Describe a DMG (partitions, checksums, signature presence). JSON result.
 * `path` is NUL-terminated OS-native path bytes, not necessarily UTF-8.
 *
 * # Safety
 *
 * `path` must point to a readable NUL-terminated string for the duration of
 * the call. `out_json` must point to writable, properly aligned storage for
 * an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_dmg_info(const char *path, struct ApplePlatformBuffer *out_json);

/**
 * Extract a partition's raw data from a DMG per `request_json`.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_data` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_dmg_extract_partition(const char *request_json,
                                             struct ApplePlatformBuffer *out_data);

/**
 * Create a simple DMG from a directory per `request_json`. Not an hdiutil
 * replacement; see package documentation for limitations.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call.
 */
int32_t apple_platform_dmg_create(const char *request_json);

/**
 * Describe a flat package installer: distribution info, component packages.
 * JSON result (upstream's serde types, verbatim). `path` is NUL-terminated
 * OS-native path bytes, not necessarily UTF-8.
 *
 * # Safety
 *
 * `path` must point to a readable NUL-terminated string for the duration of
 * the call. `out_json` must point to writable, properly aligned storage for
 * an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_pkg_info(const char *path, struct ApplePlatformBuffer *out_json);

/**
 * Extract a member file from a flat package per `request_json`.
 *
 * # Safety
 *
 * `request_json` must point to a readable NUL-terminated string for the
 * duration of the call. `out_data` must point to writable, properly aligned
 * storage for an [`ApplePlatformBuffer`]; its previous value is overwritten.
 */
int32_t apple_platform_pkg_extract_member(const char *request_json,
                                          struct ApplePlatformBuffer *out_data);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* APPLE_PLATFORM_H */
